FROM conda/miniconda3-cuda12.0-cudnn8-runtime:23.7.2
ENV PYTHON_VERSION=3.10.10
WORKDIR /choline
RUN conda install -y python=${PYTHON_VERSION}
RUN conda install -y pip
RUN pip install absl-py==1.4.0
RUN pip install altgraph==0.17.3
RUN pip install astunparse==1.6.3
RUN pip install attrs==23.1.0
RUN pip install awsgi==0.0.5
RUN pip install banana-cli==0.0.15
RUN pip install beautifulsoup4==4.12.2
RUN pip install blinker==1.6.2
RUN pip install boltons==23.0.0
RUN pip install boto3==1.28.25
RUN pip install botocore==1.31.25
RUN pip install brotlipy==0.7.0
RUN pip install bs4==0.0.1
RUN pip install CacheControl==0.13.1
RUN pip install cachetools==5.3.1
RUN pip install certifi==2022.12.7
RUN pip install cffi==1.15.1
RUN pip install chardet==4.0.0
RUN pip install charset-normalizer==3.1.0
RUN pip install click==8.1.3
RUN pip install cloudevents==1.9.0
RUN pip install cloudpickle==2.2.1
RUN pip install conda==23.7.2
RUN pip install conda-content-trust==0.1.3
RUN pip install conda-package-handling==2.0.2
RUN pip install conda_package_streaming==0.7.0
RUN pip install contourpy==1.1.0
RUN pip install cryptography==39.0.1
RUN pip install cycler==0.10.0
RUN pip install DateTime==5.1
RUN pip install decorator==4.4.2
RUN pip install deprecation==2.1.0
RUN pip install dm-tree==0.1.8
RUN pip install exceptiongroup==1.1.2
RUN pip install filelock==3.12.2
RUN pip install fire==0.5.0
RUN pip install firebase==4.0.1
RUN pip install firebase-admin==6.2.0
RUN pip install firebase-functions==0.1.1
RUN pip install Flask==2.3.2
RUN pip install Flask-Cors==4.0.0
RUN pip install flatbuffers==23.5.26
RUN pip install fonttools==4.40.0
RUN pip install fsspec==2023.6.0
RUN pip install functions-framework==3.4.0
RUN pip install gast==0.4.0
RUN pip install gitdb==4.0.10
RUN pip install GitPython==3.1.31
RUN pip install google-api-core==2.11.1
RUN pip install google-api-python-client==2.93.0
RUN pip install google-auth==2.21.0
RUN pip install google-auth-httplib2==0.1.0
RUN pip install google-auth-oauthlib==1.0.0
RUN pip install google-cloud-core==2.3.2
RUN pip install google-cloud-firestore==2.11.1
RUN pip install google-cloud-storage==2.10.0
RUN pip install google-cloud-texttospeech==2.14.1
RUN pip install google-crc32c==1.5.0
RUN pip install google-events==0.9.0
RUN pip install google-pasta==0.2.0
RUN pip install google-resumable-media==2.5.0
RUN pip install googleapis-common-protos==1.59.1
RUN pip install gpt3-package==0.1
RUN pip install gpt4all==0.3.6
RUN pip install grpcio==1.56.0
RUN pip install grpcio-status==1.56.0
RUN pip install gunicorn==20.1.0
RUN pip install h11==0.14.0
RUN pip install h5py==3.9.0
RUN pip install httplib2==0.22.0
RUN pip install httptools==0.6.0
RUN pip install huggingface-hub==0.15.1
RUN pip install idna==2.10
RUN pip install imageio==2.31.1
RUN pip install imageio-ffmpeg==0.4.8
RUN pip install importlib==1.0.4
RUN pip install itsdangerous==2.1.2
RUN pip install Jinja2==3.1.2
RUN pip install jmespath==1.0.1
RUN pip install joblib==1.3.1
RUN pip install jsonpatch==1.32
RUN pip install jsonpointer==2.1
RUN pip install keras==2.13.1rc0
RUN pip install keyboard==0.13.5
RUN pip install kiwisolver==1.4.4
RUN pip install libclang==16.0.0
RUN pip install macholib==1.16.2
RUN pip install Markdown==3.4.3
RUN pip install MarkupSafe==2.1.3
RUN pip install matplotlib==3.7.2
RUN pip install moviepy==1.0.3
RUN pip install mpmath==1.3.0
RUN pip install msgpack==1.0.5
RUN pip install networkx==3.1
RUN pip install nltk==3.8.1
RUN pip install numpy==1.25.0
RUN pip install oauthlib==3.2.2
RUN pip install onnx==1.14.0
RUN pip install onnx-tf==1.10.0
RUN pip install opencv-python==4.7.0.72
RUN pip install opencv-python-headless==4.8.0.76
RUN pip install opt-einsum==3.3.0
RUN pip install outcome==1.2.0
RUN pip install packaging==23.1
RUN pip install pafy==0.5.5
RUN pip install pandas==2.0.3
RUN pip install Pillow==9.5.0
RUN pip install pluggy==1.0.0
RUN pip install ply==3.11
RUN pip install proglog==0.1.10
RUN pip install proto-plus==1.22.3
RUN pip install protobuf==4.23.3
RUN pip install psutil==5.9.5
RUN pip install py-cpuinfo==9.0.0
RUN pip install pyasn1==0.5.0
RUN pip install pyasn1-modules==0.3.0
RUN pip install pybboxes==0.1.6
RUN pip install pycosat==0.6.4
RUN pip install pycparser==2.21
RUN pip install pydub==0.25.1
RUN pip install pygame==2.5.0
RUN pip install pyinstaller==5.13.0
RUN pip install pyinstaller-hooks-contrib==2023.6
RUN pip install PyJWT==2.7.0
RUN pip install pyobjc==9.2
RUN pip install pyobjc-core==9.2
RUN pip install pyobjc-framework-Accessibility==9.2
RUN pip install pyobjc-framework-Accounts==9.2
RUN pip install pyobjc-framework-AddressBook==9.2
RUN pip install pyobjc-framework-AdServices==9.2
RUN pip install pyobjc-framework-AdSupport==9.2
RUN pip install pyobjc-framework-AppleScriptKit==9.2
RUN pip install pyobjc-framework-AppleScriptObjC==9.2
RUN pip install pyobjc-framework-ApplicationServices==9.2
RUN pip install pyobjc-framework-AppTrackingTransparency==9.2
RUN pip install pyobjc-framework-AudioVideoBridging==9.2
RUN pip install pyobjc-framework-AuthenticationServices==9.2
RUN pip install pyobjc-framework-AutomaticAssessmentConfiguration==9.2
RUN pip install pyobjc-framework-Automator==9.2
RUN pip install pyobjc-framework-AVFoundation==9.2
RUN pip install pyobjc-framework-AVKit==9.2
RUN pip install pyobjc-framework-AVRouting==9.2
RUN pip install pyobjc-framework-BackgroundAssets==9.2
RUN pip install pyobjc-framework-BusinessChat==9.2
RUN pip install pyobjc-framework-CalendarStore==9.2
RUN pip install pyobjc-framework-CallKit==9.2
RUN pip install pyobjc-framework-CFNetwork==9.2
RUN pip install pyobjc-framework-ClassKit==9.2
RUN pip install pyobjc-framework-CloudKit==9.2
RUN pip install pyobjc-framework-Cocoa==9.2
RUN pip install pyobjc-framework-Collaboration==9.2
RUN pip install pyobjc-framework-ColorSync==9.2
RUN pip install pyobjc-framework-Contacts==9.2
RUN pip install pyobjc-framework-ContactsUI==9.2
RUN pip install pyobjc-framework-CoreAudio==9.2
RUN pip install pyobjc-framework-CoreAudioKit==9.2
RUN pip install pyobjc-framework-CoreBluetooth==9.2
RUN pip install pyobjc-framework-CoreData==9.2
RUN pip install pyobjc-framework-CoreHaptics==9.2
RUN pip install pyobjc-framework-CoreLocation==9.2
RUN pip install pyobjc-framework-CoreMedia==9.2
RUN pip install pyobjc-framework-CoreMediaIO==9.2
RUN pip install pyobjc-framework-CoreMIDI==9.2
RUN pip install pyobjc-framework-CoreML==9.2
RUN pip install pyobjc-framework-CoreMotion==9.2
RUN pip install pyobjc-framework-CoreServices==9.2
RUN pip install pyobjc-framework-CoreSpotlight==9.2
RUN pip install pyobjc-framework-CoreText==9.2
RUN pip install pyobjc-framework-CoreWLAN==9.2
RUN pip install pyobjc-framework-CryptoTokenKit==9.2
RUN pip install pyobjc-framework-DataDetection==9.2
RUN pip install pyobjc-framework-DeviceCheck==9.2
RUN pip install pyobjc-framework-DictionaryServices==9.2
RUN pip install pyobjc-framework-DiscRecording==9.2
RUN pip install pyobjc-framework-DiscRecordingUI==9.2
RUN pip install pyobjc-framework-DiskArbitration==9.2
RUN pip install pyobjc-framework-DVDPlayback==9.2
RUN pip install pyobjc-framework-EventKit==9.2
RUN pip install pyobjc-framework-ExceptionHandling==9.2
RUN pip install pyobjc-framework-ExecutionPolicy==9.2
RUN pip install pyobjc-framework-ExtensionKit==9.2
RUN pip install pyobjc-framework-ExternalAccessory==9.2
RUN pip install pyobjc-framework-FileProvider==9.2
RUN pip install pyobjc-framework-FileProviderUI==9.2
RUN pip install pyobjc-framework-FinderSync==9.2
RUN pip install pyobjc-framework-FSEvents==9.2
RUN pip install pyobjc-framework-GameCenter==9.2
RUN pip install pyobjc-framework-GameController==9.2
RUN pip install pyobjc-framework-GameKit==9.2
RUN pip install pyobjc-framework-GameplayKit==9.2
RUN pip install pyobjc-framework-HealthKit==9.2
RUN pip install pyobjc-framework-ImageCaptureCore==9.2
RUN pip install pyobjc-framework-IMServicePlugIn==9.2
RUN pip install pyobjc-framework-InputMethodKit==9.2
RUN pip install pyobjc-framework-InstallerPlugins==9.2
RUN pip install pyobjc-framework-InstantMessage==9.2
RUN pip install pyobjc-framework-Intents==9.2
RUN pip install pyobjc-framework-IntentsUI==9.2
RUN pip install pyobjc-framework-IOBluetooth==9.2
RUN pip install pyobjc-framework-IOBluetoothUI==9.2
RUN pip install pyobjc-framework-IOSurface==9.2
RUN pip install pyobjc-framework-iTunesLibrary==9.2
RUN pip install pyobjc-framework-KernelManagement==9.2
RUN pip install pyobjc-framework-LatentSemanticMapping==9.2
RUN pip install pyobjc-framework-LaunchServices==9.2
RUN pip install pyobjc-framework-libdispatch==9.2
RUN pip install pyobjc-framework-libxpc==9.2
RUN pip install pyobjc-framework-LinkPresentation==9.2
RUN pip install pyobjc-framework-LocalAuthentication==9.2
RUN pip install pyobjc-framework-LocalAuthenticationEmbeddedUI==9.2
RUN pip install pyobjc-framework-MailKit==9.2
RUN pip install pyobjc-framework-MapKit==9.2
RUN pip install pyobjc-framework-MediaAccessibility==9.2
RUN pip install pyobjc-framework-MediaLibrary==9.2
RUN pip install pyobjc-framework-MediaPlayer==9.2
RUN pip install pyobjc-framework-MediaToolbox==9.2
RUN pip install pyobjc-framework-Metal==9.2
RUN pip install pyobjc-framework-MetalFX==9.2
RUN pip install pyobjc-framework-MetalKit==9.2
RUN pip install pyobjc-framework-MetalPerformanceShaders==9.2
RUN pip install pyobjc-framework-MetalPerformanceShadersGraph==9.2
RUN pip install pyobjc-framework-MetricKit==9.2
RUN pip install pyobjc-framework-MLCompute==9.2
RUN pip install pyobjc-framework-ModelIO==9.2
RUN pip install pyobjc-framework-MultipeerConnectivity==9.2
RUN pip install pyobjc-framework-NaturalLanguage==9.2
RUN pip install pyobjc-framework-NetFS==9.2
RUN pip install pyobjc-framework-Network==9.2
RUN pip install pyobjc-framework-NetworkExtension==9.2
RUN pip install pyobjc-framework-NotificationCenter==9.2
RUN pip install pyobjc-framework-OpenDirectory==9.2
RUN pip install pyobjc-framework-OSAKit==9.2
RUN pip install pyobjc-framework-OSLog==9.2
RUN pip install pyobjc-framework-PassKit==9.2
RUN pip install pyobjc-framework-PencilKit==9.2
RUN pip install pyobjc-framework-PHASE==9.2
RUN pip install pyobjc-framework-Photos==9.2
RUN pip install pyobjc-framework-PhotosUI==9.2
RUN pip install pyobjc-framework-PreferencePanes==9.2
RUN pip install pyobjc-framework-PushKit==9.2
RUN pip install pyobjc-framework-Quartz==9.2
RUN pip install pyobjc-framework-QuickLookThumbnailing==9.2
RUN pip install pyobjc-framework-ReplayKit==9.2
RUN pip install pyobjc-framework-SafariServices==9.2
RUN pip install pyobjc-framework-SafetyKit==9.2
RUN pip install pyobjc-framework-SceneKit==9.2
RUN pip install pyobjc-framework-ScreenCaptureKit==9.2
RUN pip install pyobjc-framework-ScreenSaver==9.2
RUN pip install pyobjc-framework-ScreenTime==9.2
RUN pip install pyobjc-framework-ScriptingBridge==9.2
RUN pip install pyobjc-framework-SearchKit==9.2
RUN pip install pyobjc-framework-Security==9.2
RUN pip install pyobjc-framework-SecurityFoundation==9.2
RUN pip install pyobjc-framework-SecurityInterface==9.2
RUN pip install pyobjc-framework-ServiceManagement==9.2
RUN pip install pyobjc-framework-SharedWithYou==9.2
RUN pip install pyobjc-framework-SharedWithYouCore==9.2
RUN pip install pyobjc-framework-ShazamKit==9.2
RUN pip install pyobjc-framework-Social==9.2
RUN pip install pyobjc-framework-SoundAnalysis==9.2
RUN pip install pyobjc-framework-Speech==9.2
RUN pip install pyobjc-framework-SpriteKit==9.2
RUN pip install pyobjc-framework-StoreKit==9.2
RUN pip install pyobjc-framework-SyncServices==9.2
RUN pip install pyobjc-framework-SystemConfiguration==9.2
RUN pip install pyobjc-framework-SystemExtensions==9.2
RUN pip install pyobjc-framework-ThreadNetwork==9.2
RUN pip install pyobjc-framework-UniformTypeIdentifiers==9.2
RUN pip install pyobjc-framework-UserNotifications==9.2
RUN pip install pyobjc-framework-UserNotificationsUI==9.2
RUN pip install pyobjc-framework-VideoSubscriberAccount==9.2
RUN pip install pyobjc-framework-VideoToolbox==9.2
RUN pip install pyobjc-framework-Virtualization==9.2
RUN pip install pyobjc-framework-Vision==9.2
RUN pip install pyobjc-framework-WebKit==9.2
RUN pip install pyOpenSSL==23.0.0
RUN pip install pyparsing==2.4.7
RUN pip install PyQt5-sip==12.11.0
RUN pip install PySocks==1.7.1
RUN pip install python-dateutil==2.8.2
RUN pip install python-dotenv==1.0.0
RUN pip install python-vlc==3.0.18122
RUN pip install pytube==15.0.0
RUN pip install pytz==2023.3
RUN pip install PyYAML==6.0
RUN pip install regex==2023.6.3
RUN pip install requests==2.31.0
RUN pip install requests-oauthlib==1.3.1
RUN pip install requests-toolbelt==1.0.0
RUN pip install roboflow==1.1.2
RUN pip install rsa==4.9
RUN pip install ruamel.yaml==0.17.21
RUN pip install ruamel.yaml.clib==0.2.6
RUN pip install s3transfer==0.6.1
RUN pip install safetensors==0.3.1
RUN pip install sahi==0.11.14
RUN pip install scikit-learn==1.3.0
RUN pip install scipy==1.11.1
RUN pip install seaborn==0.12.2
RUN pip install selenium==4.11.2
RUN pip install sentence-transformers==2.2.2
RUN pip install sentencepiece==0.1.99
RUN pip install shapely==2.0.1
RUN pip install sip==6.6.2
RUN pip install six==1.16.0
RUN pip install smmap==5.0.0
RUN pip install sniffio==1.3.0
RUN pip install sortedcontainers==2.4.0
RUN pip install soupsieve==2.4.1
RUN pip install supervision==0.13.0
RUN pip install sympy==1.12
RUN pip install tensorboard==2.13.0
RUN pip install tensorboard-data-server==0.7.1
RUN pip install tensorboard-plugin-wit==1.8.1
RUN pip install tensorflow==2.13.0rc1
RUN pip install tensorflow-addons==0.21.0
RUN pip install tensorflow-estimator==2.13.0rc0
RUN pip install tensorflow-macos==2.13.0rc1
RUN pip install tensorflow-probability==0.21.0
RUN pip install termcolor==2.3.0
RUN pip install terminaltables==3.1.10
RUN pip install thop==0.1.1.post2209072238
RUN pip install threadpoolctl==3.1.0
RUN pip install tk==0.1.0
RUN pip install tokenizers==0.13.3
RUN pip install toml==0.10.2
RUN pip install toolz==0.12.0
RUN pip install torch==2.0.1
RUN pip install torchvision==0.15.2
RUN pip install tqdm==4.65.0
RUN pip install transformers==4.30.2
RUN pip install trio==0.22.1
RUN pip install trio-websocket==0.10.3
RUN pip install typeguard==2.13.3
RUN pip install typing_extensions==4.5.0
RUN pip install tzdata==2023.3
RUN pip install ultralytics==8.0.153
RUN pip install uritemplate==4.1.1
RUN pip install urllib3==1.26.16
RUN pip install urllib3-secure-extra==0.1.0
RUN pip install uvloop==0.17.0
RUN pip install vastai==0.1.7
RUN pip install watchdog==3.0.0
RUN pip install websockets==11.0.3
RUN pip install Werkzeug==2.3.6
RUN pip install wget==3.2
RUN pip install wrapt==1.15.0
RUN pip install wsproto==1.2.0
RUN pip install yolov5==7.0.12
RUN pip install youtube-dl==2021.12.17
RUN pip install zope.interface==6.0
RUN pip install zstandard==0.19.0
RUN pip install 