// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhPVyEJ4p8bEVNiXjHKF1p7ca-5bPttkg',
    appId: '1:336610753327:web:c8cde61505bbad6f9fffda',
    messagingSenderId: '336610753327',
    projectId: 'mlhero-c6fc8',
    authDomain: 'mlhero-c6fc8.firebaseapp.com',
    databaseURL: 'https://mlhero-c6fc8-default-rtdb.firebaseio.com',
    storageBucket: 'mlhero-c6fc8.appspot.com',
    measurementId: 'G-HL49E277J0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgxVvIyOOXF-CTuo8RtymxWL43W6HoF-M',
    appId: '1:336610753327:android:b5e8957628bd9f4c9fffda',
    messagingSenderId: '336610753327',
    projectId: 'mlhero-c6fc8',
    databaseURL: 'https://mlhero-c6fc8-default-rtdb.firebaseio.com',
    storageBucket: 'mlhero-c6fc8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOEs8AHahO0Q9D8nBgW2PnICmb4jugE5w',
    appId: '1:336610753327:ios:256bd2f37b7970b49fffda',
    messagingSenderId: '336610753327',
    projectId: 'mlhero-c6fc8',
    databaseURL: 'https://mlhero-c6fc8-default-rtdb.firebaseio.com',
    storageBucket: 'mlhero-c6fc8.appspot.com',
    iosClientId: '336610753327-72ujpnokd6j84cb8n9d1k3ss63bu80r8.apps.googleusercontent.com',
    iosBundleId: 'com.example.runnable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOEs8AHahO0Q9D8nBgW2PnICmb4jugE5w',
    appId: '1:336610753327:ios:256bd2f37b7970b49fffda',
    messagingSenderId: '336610753327',
    projectId: 'mlhero-c6fc8',
    databaseURL: 'https://mlhero-c6fc8-default-rtdb.firebaseio.com',
    storageBucket: 'mlhero-c6fc8.appspot.com',
    iosClientId: '336610753327-72ujpnokd6j84cb8n9d1k3ss63bu80r8.apps.googleusercontent.com',
    iosBundleId: 'com.example.runnable',
  );
}
